version: 2

models:
  - name: dbt_dim_symbols
    description: Gold dimension model containing tradable symbols.
    columns:
      - name: symbol
        tests:
          - not_null
          - unique

  - name: dbt_fact_daily_prices
    description: Gold fact model containing analytics-ready daily OHLCV observations.
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: close
        tests:
          - not_null
